# Hallgatók namespace-ei
apiVersion: v1
kind: Namespace
metadata:
  name: student-laci
---
apiVersion: v1
kind: Namespace
metadata:
  name: student-lajos
---
apiVersion: v1
kind: Namespace
metadata:
  name: student-peti
---
# Kiértékelő rendszer - hallgatók elől rejtve
apiVersion: v1
kind: Namespace
metadata:
  name: exam-system
---
# Admin namespace
apiVersion: v1
kind: Namespace
metadata:
  name: admin