# ---- lajos's service account ----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lajos
  namespace: student-lajos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-role
  namespace: student-lajos
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "delete", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lajos-binding
  namespace: student-lajos
subjects:
- kind: ServiceAccount
  name: lajos
  namespace: student-lajos
roleRef:
  kind: Role
  name: student-role
  apiGroup: rbac.authorization.k8s.io

---
# ---- laci's service account ----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: laci
  namespace: student-laci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-role
  namespace: student-laci
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "delete", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: laci-binding
  namespace: student-laci
subjects:
- kind: ServiceAccount
  name: laci
  namespace: student-laci
roleRef:
  kind: Role
  name: student-role
  apiGroup: rbac.authorization.k8s.io

---
# ---- peti's service account ----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: peti
  namespace: student-peti
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-role
  namespace: student-peti
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "delete", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: peti-binding
  namespace: student-peti
subjects:
- kind: ServiceAccount
  name: peti
  namespace: student-peti
roleRef:
  kind: Role
  name: student-role
  apiGroup: rbac.authorization.k8s.io